-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.courses
(
    id serial NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default",
    front_tee text COLLATE pg_catalog."default",
    back_tee text COLLATE pg_catalog."default",
    website text COLLATE pg_catalog."default",
    scorecard jsonb,
    image_path text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT courses_pkey PRIMARY KEY (id),
    CONSTRAINT courses_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.event_players
(
    id serial NOT NULL,
    event_id integer NOT NULL,
    player_id integer NOT NULL,
    quota integer NOT NULL DEFAULT 0,
    score integer NOT NULL DEFAULT 0,
    ctps integer DEFAULT 0,
    skins integer DEFAULT 0,
    money_won numeric DEFAULT 0.0,
    rank integer,
    total_points numeric DEFAULT 0.0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT event_players_pkey PRIMARY KEY (id),
    CONSTRAINT event_player_unique UNIQUE (event_id, player_id)
);

CREATE TABLE IF NOT EXISTS public.events
(
    id serial NOT NULL,
    course_id integer NOT NULL,
    date date NOT NULL,
    is_major boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.players
(
    id serial NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default",
    phone_number text COLLATE pg_catalog."default",
    image_path text COLLATE pg_catalog."default",
    current_quota integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT players_pkey PRIMARY KEY (id),
    CONSTRAINT players_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.points_config
(
    id serial NOT NULL,
    key character varying(50) COLLATE pg_catalog."default" NOT NULL,
    value integer NOT NULL,
    ctp_skin_cap integer DEFAULT 10,
    CONSTRAINT points_config_pkey PRIMARY KEY (id),
    CONSTRAINT points_config_key_key UNIQUE (key)
);

ALTER TABLE IF EXISTS public.event_players
    ADD CONSTRAINT event_players_player_id_fkey FOREIGN KEY (player_id)
    REFERENCES public.players (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.events
    ADD CONSTRAINT events_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.courses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;