name: Frontend Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REPO }}/frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: SSH into Unraid and Deploy
        uses: appleboy/ssh-action@v0.1.11
        with:
          host: ${{ secrets.UNRAID_HOST }}
          username: ${{ secrets.UNRAID_USER }}
          password: ${{ secrets.UNRAID_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_REPO }}/frontend:latest
            docker stop wanker-league-frontend || true
            docker rm wanker-league-frontend || true
            docker run -d --name wanker-league-frontend -p 3000:80 ${{ secrets.DOCKER_REPO }}/frontend:latest
